### ISSUE TITLE
Crash on windows 7

### ISSUE THREAD

**Issue by FaffeF** [microsoft/etl2pcapng#21]
The tool crashes on Windows 7 and Server 2008 R2, no matter if the input file exists or not.

Vanilla Win 7 SP1, vc_redist.x64 installed.

```yaml
Log Name:      Application
Source:        Application Error
Date:          2020-02-26 08:44:38
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:     [redacted]
Description:
Faulting application name: etl2pcapng.exe, version: 0.0.0.0, time stamp: 0x5e123992
Faulting module name: KERNELBASE.dll, version: 6.1.7601.17514, time stamp: 0x4ce7c78c
Exception code: 0xc0000005
Fault offset: 0x0000000000001ba4
Faulting process id: 0x694
Faulting application start time: 0x01d5ec7899325f47
Faulting application path: C:\temp\etl2pcapng.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: d6dee9fe-586b-11ea-85c8-0050568ea07c
```
